# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(424, 735)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(login.sizePolicy().hasHeightForWidth())
        login.setSizePolicy(sizePolicy)
        login.setAutoFillBackground(False)
        login.setStyleSheet("border-image: url(:/resource/img/color.jpg);\n"
                            "QWidget#reg {\n"
                            "        border-top-left-radius: 15px;\n"
                            "        border-bottom-left-radius: 15px;\n"
                            "        border-top-right-radius: 15px;\n"
                            "        border-bottom-right-radius: 15px;\n"
                            "        border: 2px solid white;        \n"
                            "}")
        self.verticalLayout = QtWidgets.QVBoxLayout(login)
        self.verticalLayout.setContentsMargins(5, 5, 5, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(login)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color:white;\n"
                                       "font: 85 25pt \"Microsoft YaHei\";\n"
                                       "font-weight:bold;\n"
                                       "border-image:None;\n"
                                       "\n"
                                       "\n"
                                       "\n"
                                       "")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.line_2 = QtWidgets.QFrame(login)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.widget_cam = QtWidgets.QWidget(login)
        self.widget_cam.setStyleSheet("border-image: None;\n"
                                      "QWidget#widget_cam {\n"
                                      "    border: 2px solid white;\n"
                                      "    border-radius: 40px;\n"
                                      "}\n"
                                      "")
        self.widget_cam.setObjectName("widget_cam")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_cam)
        self.gridLayout_2.setContentsMargins(25, 10, 25, 10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_cam = QtWidgets.QLabel(self.widget_cam)
        self.label_cam.setStyleSheet("border-radius: 20px;")
        self.label_cam.setText("")
        self.label_cam.setObjectName("label_cam")
        self.gridLayout_2.addWidget(self.label_cam, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_cam)
        self.line = QtWidgets.QFrame(login)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.widget_input = QtWidgets.QWidget(login)
        self.widget_input.setStyleSheet("border-image: None;")
        self.widget_input.setObjectName("widget_input")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_input)
        self.gridLayout.setContentsMargins(50, 1, 50, 1)
        self.gridLayout.setHorizontalSpacing(2)
        self.gridLayout.setVerticalSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.widget_input)
        self.label.setStyleSheet("border-image: url(:/resource/img/Dark_人脸识别.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 2, 2)
        self.btn_reget = QtWidgets.QPushButton(self.widget_input)
        self.btn_reget.setMinimumSize(QtCore.QSize(75, 0))
        self.btn_reget.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.btn_reget.setFont(font)
        self.btn_reget.setStyleSheet("QPushButton\n"
                                     "{\n"
                                     "    border-radius: 10px;\n"
                                     "    padding:5px;\n"
                                     "    text-align: center;\n"
                                     "    text-decoration: none;\n"
                                     "    font-size:14px;\n"
                                     "    margin: 4px 2px;\n"
                                     "    background-color: white;\n"
                                     "    color:#1d4181;\n"
                                     "    border:1px solid #1d4181;\n"
                                     "}\n"
                                     "QPushButton:hover \n"
                                     "{\n"
                                     "    background-color: #008cba;\n"
                                     "    color: white;\n"
                                     "}\n"
                                     "QPushButton:pressed \n"
                                     "{\n"
                                     "    margin-top: -2px;\n"
                                     "    margin-bottom:2px;\n"
                                     "    \n"
                                     "}\n"
                                     "")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resource/icon/redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_reget.setIcon(icon)
        self.btn_reget.setObjectName("btn_reget")
        self.gridLayout_3.addWidget(self.btn_reget, 2, 2, 1, 1)
        self.btn_get_face = QtWidgets.QPushButton(self.widget_input)
        self.btn_get_face.setMinimumSize(QtCore.QSize(75, 0))
        self.btn_get_face.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.btn_get_face.setFont(font)
        self.btn_get_face.setStyleSheet("QPushButton\n"
                                        "{\n"
                                        "    border-radius: 10px;\n"
                                        "    padding:5px;\n"
                                        "    text-align: center;\n"
                                        "    text-decoration: none;\n"
                                        "    font-size:14px;\n"
                                        "    margin: 4px 2px;\n"
                                        "    background-color: white;\n"
                                        "    color:#1d4181;\n"
                                        "    border:1px solid #1d4181;\n"
                                        "}\n"
                                        "QPushButton:hover \n"
                                        "{\n"
                                        "    background-color: #008cba;\n"
                                        "    color: white;\n"
                                        "}\n"
                                        "QPushButton:pressed \n"
                                        "{\n"
                                        "    margin-top: -2px;\n"
                                        "    margin-bottom:2px;\n"
                                        "    \n"
                                        "}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resource/icon/人脸识别.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_get_face.setIcon(icon1)
        self.btn_get_face.setObjectName("btn_get_face")
        self.gridLayout_3.addWidget(self.btn_get_face, 1, 2, 1, 1)
        self.btn_connect = QtWidgets.QPushButton(self.widget_input)
        self.btn_connect.setMaximumSize(QtCore.QSize(180, 35))
        self.btn_connect.setStyleSheet("QPushButton\n"
                                       "{\n"
                                       "    border-radius: 10px;\n"
                                       "    padding:5px;\n"
                                       "    text-align: center;\n"
                                       "    text-decoration: none;\n"
                                       "    font-size:12px;\n"
                                       "    margin: 4px 2px;\n"
                                       "    background-color: white;\n"
                                       "    color:#1d4181;\n"
                                       "    border:1px solid black;\n"
                                       "}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/resource/icon/提醒,感叹号_jurassic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_connect.setIcon(icon2)
        self.btn_connect.setObjectName("btn_connect")
        self.gridLayout_3.addWidget(self.btn_connect, 0, 1, 1, 1)
        self.gridLayout_3.setRowStretch(0, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 0, 1, 2)
        self.verticalLayout.addWidget(self.widget_input)
        self.layout_decide = QtWidgets.QHBoxLayout()
        self.layout_decide.setContentsMargins(50, -1, 50, -1)
        self.layout_decide.setSpacing(20)
        self.layout_decide.setObjectName("layout_decide")
        self.btn_decide = QtWidgets.QPushButton(login)
        self.btn_decide.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        self.btn_decide.setFont(font)
        self.btn_decide.setStyleSheet("\n"
                                      "QPushButton\n"
                                      "{\n"
                                      "font-size:16px;\n"
                                      "border-radius:16px;\n"
                                      "border:2px solid green;\n"
                                      "background:white;\n"
                                      "}\n"
                                      "QPushButton:hover \n"
                                      "{\n"
                                      "    color:rgb(97, 97, 97)\n"
                                      "}\n"
                                      "QPushButton:pressed \n"
                                      "{\n"
                                      "    margin-top: -2px;\n"
                                      "    margin-bottom:2px;\n"
                                      "    \n"
                                      "}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/resource/icon/check-circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_decide.setIcon(icon3)
        self.btn_decide.setObjectName("btn_decide")
        self.layout_decide.addWidget(self.btn_decide)
        self.btn_reg = QtWidgets.QPushButton(login)
        self.btn_reg.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        self.btn_reg.setFont(font)
        self.btn_reg.setStyleSheet("QPushButton\n"
                                   "{\n"
                                   "font-size:16px;\n"
                                   "border-radius:16px;\n"
                                   "border:2px solid green;\n"
                                   "background:white;\n"
                                   "}\n"
                                   "QPushButton:hover \n"
                                   "{\n"
                                   "    color:rgb(97, 97, 97)\n"
                                   "}\n"
                                   "QPushButton:pressed \n"
                                   "{\n"
                                   "    margin-top: -2px;\n"
                                   "    margin-bottom:2px;\n"
                                   "    \n"
                                   "}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/resource/icon/用户.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_reg.setIcon(icon4)
        self.btn_reg.setObjectName("btn_reg")
        self.layout_decide.addWidget(self.btn_reg)
        self.btn_return = QtWidgets.QPushButton(login)
        self.btn_return.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        self.btn_return.setFont(font)
        self.btn_return.setStyleSheet("QPushButton{\n"
                                      "font-size:16px;\n"
                                      "border-radius:16px;\n"
                                      "border:2px solid green;\n"
                                      "background:white;\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:hover \n"
                                      "{\n"
                                      "    color:rgb(97, 97, 97)\n"
                                      "}\n"
                                      "QPushButton:pressed \n"
                                      "{\n"
                                      "    margin-top: -2px;\n"
                                      "    margin-bottom:2px;\n"
                                      "    \n"
                                      "}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/resource/icon/返回.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_return.setIcon(icon5)
        self.btn_return.setObjectName("btn_return")
        self.layout_decide.addWidget(self.btn_return)
        self.verticalLayout.addLayout(self.layout_decide)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(2, 8)
        self.verticalLayout.setStretch(4, 5)
        self.verticalLayout.setStretch(5, 2)

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "登陆界面"))
        self.label_title.setText(_translate("login", ">> 登 陆 <<"))
        self.btn_reget.setText(_translate("login", "重新捕获"))
        self.btn_get_face.setText(_translate("login", "捕获人脸"))
        self.btn_connect.setText(_translate("login", "服务器连接失败!"))
        self.btn_decide.setText(_translate("login", "确  认"))
        self.btn_reg.setText(_translate("login", "注 册"))
        self.btn_return.setText(_translate("login", "返  回"))


import ui_file.resource_rc
