# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_reg.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_reg(object):
    def setupUi(self, reg):
        reg.setObjectName("reg")
        reg.resize(424, 735)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(reg.sizePolicy().hasHeightForWidth())
        reg.setSizePolicy(sizePolicy)
        reg.setAutoFillBackground(False)
        reg.setStyleSheet("border-image: url(:/resource/img/color.jpg);\n"
                          "QWidget#reg {\n"
                          "        border-top-left-radius: 15px;\n"
                          "        border-bottom-left-radius: 15px;\n"
                          "        border-top-right-radius: 15px;\n"
                          "        border-bottom-right-radius: 15px;\n"
                          "        border: 2px solid white;        \n"
                          "}")
        self.verticalLayout = QtWidgets.QVBoxLayout(reg)
        self.verticalLayout.setContentsMargins(5, 5, 5, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(reg)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color:white;\n"
                                       "font: 85 25pt \"Microsoft YaHei\";\n"
                                       "font-weight:bold;\n"
                                       "border-image:None;\n"
                                       "\n"
                                       "\n"
                                       "\n"
                                       "")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.line_2 = QtWidgets.QFrame(reg)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.widget_cam = QtWidgets.QWidget(reg)
        self.widget_cam.setStyleSheet("border-image: None;\n"
                                      "QWidget#widget_cam {\n"
                                      "    border: 2px solid white;\n"
                                      "    border-radius: 40px;\n"
                                      "}\n"
                                      "")
        self.widget_cam.setObjectName("widget_cam")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_cam)
        self.gridLayout_2.setContentsMargins(25, 10, 25, 10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_cam = QtWidgets.QLabel(self.widget_cam)
        self.label_cam.setStyleSheet("border-radius: 20px;")
        self.label_cam.setText("")
        self.label_cam.setObjectName("label_cam")
        self.gridLayout_2.addWidget(self.label_cam, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_cam)
        self.line = QtWidgets.QFrame(reg)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.widget_input = QtWidgets.QWidget(reg)
        self.widget_input.setStyleSheet("border-image: None;")
        self.widget_input.setObjectName("widget_input")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_input)
        self.gridLayout.setContentsMargins(50, 0, 50, 1)
        self.gridLayout.setHorizontalSpacing(2)
        self.gridLayout.setVerticalSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.widget_input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(25)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(25, 25))
        self.label_5.setMaximumSize(QtCore.QSize(50, 20))
        self.label_5.setStyleSheet("border-image: url(:/resource/icon/时间.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(15)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_get_face = QtWidgets.QPushButton(self.widget_input)
        self.btn_get_face.setMinimumSize(QtCore.QSize(75, 0))
        self.btn_get_face.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.btn_get_face.setFont(font)
        self.btn_get_face.setStyleSheet("QPushButton\n"
                                        "{\n"
                                        "    border-radius: 10px;\n"
                                        "    padding:5px;\n"
                                        "    text-align: center;\n"
                                        "    text-decoration: none;\n"
                                        "    font-size:14px;\n"
                                        "    margin: 4px 2px;\n"
                                        "    background-color: white;\n"
                                        "    color:#1d4181;\n"
                                        "    border:1px solid #1d4181;\n"
                                        "}\n"
                                        "QPushButton:hover \n"
                                        "{\n"
                                        "    background-color: #008cba;\n"
                                        "    color: white;\n"
                                        "}\n"
                                        "QPushButton:pressed \n"
                                        "{\n"
                                        "    margin-top: -2px;\n"
                                        "    margin-bottom:2px;\n"
                                        "    \n"
                                        "}")
        self.btn_get_face.setObjectName("btn_get_face")
        self.horizontalLayout_4.addWidget(self.btn_get_face)
        self.btn_reget = QtWidgets.QPushButton(self.widget_input)
        self.btn_reget.setMinimumSize(QtCore.QSize(75, 0))
        self.btn_reget.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.btn_reget.setFont(font)
        self.btn_reget.setStyleSheet("QPushButton\n"
                                     "{\n"
                                     "    border-radius: 10px;\n"
                                     "    padding:5px;\n"
                                     "    text-align: center;\n"
                                     "    text-decoration: none;\n"
                                     "    font-size:14px;\n"
                                     "    margin: 4px 2px;\n"
                                     "    background-color: white;\n"
                                     "    color:#1d4181;\n"
                                     "    border:1px solid #1d4181;\n"
                                     "}\n"
                                     "QPushButton:hover \n"
                                     "{\n"
                                     "    background-color: #008cba;\n"
                                     "    color: white;\n"
                                     "}\n"
                                     "QPushButton:pressed \n"
                                     "{\n"
                                     "    margin-top: -2px;\n"
                                     "    margin-bottom:2px;\n"
                                     "    \n"
                                     "}\n"
                                     "")
        self.btn_reget.setObjectName("btn_reget")
        self.horizontalLayout_4.addWidget(self.btn_reget)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 2, 1, 3)
        self.label_6 = QtWidgets.QLabel(self.widget_input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(25)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(25, 25))
        self.label_6.setMaximumSize(QtCore.QSize(50, 20))
        self.label_6.setStyleSheet("border-image: url(:/resource/icon/人脸识别.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_input)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget_input)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_input)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 1, 1, 1)
        self.edit_time = QtWidgets.QLineEdit(self.widget_input)
        self.edit_time.setMinimumSize(QtCore.QSize(75, 0))
        self.edit_time.setMaximumSize(QtCore.QSize(500, 500))
        self.edit_time.setStyleSheet("background: transparent;\n"
                                     "color:rgb(0, 0, 0);\n"
                                     "border-width:1px;border-style:none none solid none;border-color:black;\n"
                                     "width:100%;\n"
                                     "font-size:14px;\n"
                                     "height:20px;\n"
                                     "line-height:25px;\n"
                                     "padding:4px;\n"
                                     "")
        self.edit_time.setAlignment(QtCore.Qt.AlignCenter)
        self.edit_time.setReadOnly(True)
        self.edit_time.setObjectName("edit_time")
        self.gridLayout.addWidget(self.edit_time, 2, 2, 1, 3)
        self.label_4 = QtWidgets.QLabel(self.widget_input)
        self.label_4.setMinimumSize(QtCore.QSize(25, 25))
        self.label_4.setMaximumSize(QtCore.QSize(25, 25))
        self.label_4.setStyleSheet("border-image: url(:/resource/icon/用户.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.edit_user_name = QtWidgets.QLineEdit(self.widget_input)
        self.edit_user_name.setMinimumSize(QtCore.QSize(75, 0))
        self.edit_user_name.setMaximumSize(QtCore.QSize(500, 500))
        self.edit_user_name.setStyleSheet("border:1px solid black;  \n"
                                          "width:100%;\n"
                                          "font-size:14px;\n"
                                          "height:20px;\n"
                                          "line-height:24px;\n"
                                          "padding:5px;")
        self.edit_user_name.setText("")
        self.edit_user_name.setMaxLength(10)
        self.edit_user_name.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.edit_user_name.setClearButtonEnabled(True)
        self.edit_user_name.setObjectName("edit_user_name")
        self.gridLayout.addWidget(self.edit_user_name, 1, 2, 1, 3)
        self.pushButton = QtWidgets.QPushButton(self.widget_input)
        self.pushButton.setMaximumSize(QtCore.QSize(180, 35))
        self.pushButton.setStyleSheet("QPushButton\n"
                                      "{\n"
                                      "    border-radius: 10px;\n"
                                      "    padding:5px;\n"
                                      "    text-align: center;\n"
                                      "    text-decoration: none;\n"
                                      "    font-size:12px;\n"
                                      "    margin: 4px 2px;\n"
                                      "    background-color: white;\n"
                                      "    color:#1d4181;\n"
                                      "    border:1px solid black;\n"
                                      "}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resource/icon/提醒,感叹号_jurassic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 2, 1, 2)
        self.verticalLayout.addWidget(self.widget_input)
        self.layout_decide = QtWidgets.QHBoxLayout()
        self.layout_decide.setContentsMargins(50, -1, 50, -1)
        self.layout_decide.setSpacing(20)
        self.layout_decide.setObjectName("layout_decide")
        self.btn_decide = QtWidgets.QPushButton(reg)
        self.btn_decide.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        self.btn_decide.setFont(font)
        self.btn_decide.setStyleSheet("\n"
                                      "QPushButton\n"
                                      "{\n"
                                      "font-size:16px;\n"
                                      "border-radius:16px;\n"
                                      "border:2px solid green;\n"
                                      "background:white;\n"
                                      "}\n"
                                      "QPushButton:hover \n"
                                      "{\n"
                                      "    color:rgb(97, 97, 97)\n"
                                      "}\n"
                                      "QPushButton:pressed \n"
                                      "{\n"
                                      "    margin-top: -2px;\n"
                                      "    margin-bottom:2px;\n"
                                      "    \n"
                                      "}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resource/icon/check-circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_decide.setIcon(icon1)
        self.btn_decide.setObjectName("btn_decide")
        self.layout_decide.addWidget(self.btn_decide)
        self.btn_return = QtWidgets.QPushButton(reg)
        self.btn_return.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        self.btn_return.setFont(font)
        self.btn_return.setStyleSheet("QPushButton{\n"
                                      "font-size:16px;\n"
                                      "border-radius:16px;\n"
                                      "border:2px solid green;\n"
                                      "background:white;\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:hover \n"
                                      "{\n"
                                      "    color:rgb(97, 97, 97)\n"
                                      "}\n"
                                      "QPushButton:pressed \n"
                                      "{\n"
                                      "    margin-top: -2px;\n"
                                      "    margin-bottom:2px;\n"
                                      "    \n"
                                      "}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/resource/icon/返回.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_return.setIcon(icon2)
        self.btn_return.setObjectName("btn_return")
        self.layout_decide.addWidget(self.btn_return)
        self.verticalLayout.addLayout(self.layout_decide)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(2, 8)
        self.verticalLayout.setStretch(4, 5)
        self.verticalLayout.setStretch(5, 2)

        self.retranslateUi(reg)
        QtCore.QMetaObject.connectSlotsByName(reg)

    def retranslateUi(self, reg):
        _translate = QtCore.QCoreApplication.translate
        reg.setWindowTitle(_translate("reg", "注册界面"))
        self.label_title.setText(_translate("reg", ">> 注 册 <<"))
        self.btn_get_face.setText(_translate("reg", "捕获人脸"))
        self.btn_reget.setText(_translate("reg", "重新捕获"))
        self.label_2.setText(_translate("reg", "时间:"))
        self.label.setText(_translate("reg", "名称:"))
        self.label_3.setText(_translate("reg", "识别:"))
        self.edit_user_name.setPlaceholderText(_translate("reg", "   请输入用户名称"))
        self.pushButton.setText(_translate("reg", "服务器连接失败"))
        self.btn_decide.setText(_translate("reg", "确  认"))
        self.btn_return.setText(_translate("reg", "返  回"))
        

import ui_file.resource_rc
