# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_start.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_start(object):
    def setupUi(self, start):
        start.setObjectName("start")
        start.setEnabled(True)
        start.resize(822, 593)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(start.sizePolicy().hasHeightForWidth())
        start.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resource/icon/resource/icon/人脸核身.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        start.setWindowIcon(icon)
        start.setAutoFillBackground(False)
        start.setStyleSheet("border-image: url(:/resource/img/main.jpg);")
        self.btn_face_reg = QtWidgets.QPushButton(start)
        self.btn_face_reg.setGeometry(QtCore.QRect(540, 270, 151, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        self.btn_face_reg.setFont(font)
        self.btn_face_reg.setStyleSheet("QPushButton{\n"
                                        "background:white;\n"
                                        "border-radius:10px;\n"
                                        "border: 1px solid;\n"
                                        "border-image: white;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed\n"
                                        "{\n"
                                        "   background-color: rgb(0, 85, 255);\n"
                                        "   border-style: inset;\n"
                                        "   margin-top: -10px;\n"
                                        "   margin-bottom: -10px;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover\n"
                                        "{\n"
                                        "background-color: rgb(0, 255, 255);\n"
                                        "}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resource/icon/爸爸.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_face_reg.setIcon(icon1)
        self.btn_face_reg.setObjectName("btn_face_reg")
        self.btn_face_recognition = QtWidgets.QPushButton(start)
        self.btn_face_recognition.setGeometry(QtCore.QRect(540, 330, 151, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        self.btn_face_recognition.setFont(font)
        self.btn_face_recognition.setStyleSheet("QPushButton{\n"
                                                "background:white;\n"
                                                "border-radius:10px;\n"
                                                "border: 1px solid;\n"
                                                "border-image: white;\n"
                                                "}\n"
                                                "\n"
                                                "QPushButton:pressed\n"
                                                "{\n"
                                                "   background-color: rgb(0, 85, 255);\n"
                                                "   border-style: inset;\n"
                                                "   margin-top: -10px;\n"
                                                "   margin-bottom: -10px;\n"
                                                "}\n"
                                                "\n"
                                                "QPushButton:hover\n"
                                                "{\n"
                                                "background-color: rgb(0, 255, 255);\n"
                                                "}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/resource/icon/人脸核身.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_face_recognition.setIcon(icon2)
        self.btn_face_recognition.setObjectName("btn_face_recognition")
        self.btn_exit = QtWidgets.QPushButton(start)
        self.btn_exit.setGeometry(QtCore.QRect(540, 390, 151, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet("QPushButton{\n"
                                    "background:white;\n"
                                    "border-radius:10px;\n"
                                    "border: 1px solid;\n"
                                    "border-image: white;\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:pressed\n"
                                    "{\n"
                                    "   background-color: rgb(0, 85, 255);\n"
                                    "   border-style: inset;\n"
                                    "   margin-top: -10px;\n"
                                    "   margin-bottom: -10px;\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:hover\n"
                                    "{\n"
                                    "background-color: rgb(0, 255, 255);\n"
                                    "}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/resource/icon/拉钩.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_exit.setIcon(icon3)
        self.btn_exit.setObjectName("btn_exit")
        self.label = QtWidgets.QLabel(start)
        self.label.setGeometry(QtCore.QRect(510, 210, 211, 51))
        self.label.setStyleSheet("font-family: \"Microsoft YaHei\";\n"
                                 "font-size: 25px;\n"
                                 "font-style: italic;\n"
                                 "font-weight: bold;\n"
                                 "color: white;\n"
                                 "font: bold italic 25px \"Microsoft YaHei\";\n"
                                 "border-image: url(:/resource/img/resource/img/reg.jpg);\n"
                                 "border-image: white;\n"
                                 "\n"
                                 "\n"
                                 "\n"
                                 "")
        self.label.setObjectName("label")

        self.retranslateUi(start)
        QtCore.QMetaObject.connectSlotsByName(start)

    def retranslateUi(self, start):
        _translate = QtCore.QCoreApplication.translate
        start.setWindowTitle(_translate("start", "智能校园防护系统主界面"))
        self.btn_face_reg.setText(_translate("start", "人脸注册"))
        self.btn_face_recognition.setText(_translate("start", "开启识别"))
        self.btn_exit.setText(_translate("start", "退出程序"))
        self.label.setText(_translate("start", "智能校园防御系统"))


import ui_file.resource_rc
